# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370d3818a30a1ae97a270919919a7e0444052a1c94302b190e079003ee00c71c5656e57643ac3984fff25a02da9fe85c29d46629d8f4b64e3d5027724862b265

test:
  secret_key_base: 4ec5f23202ac11bfb60db971c055bbc7a01d8ae5388d2e725a2112e518ba059718baa2c8744d323df9f1252535540b73a6fe1c8937db394d52645b9d46e67906

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
